'use strict';
(() => {
const state={products:[],filter:'all',sort:'featured',wishlist:readJSON('verveWishlist',[]),cart:readJSON('verveCart',[]),selectedProduct:null,selectedSize:null,drawer:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function readJSON(key,fallback=[]){try{const v=JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));return Array.isArray(v)?v:fallback}catch{return fallback}}
function persist(){try{localStorage.setItem('verveWishlist',JSON.stringify(state.wishlist));localStorage.setItem('verveCart',JSON.stringify(state.cart));}catch{toast('Storage unavailable in this browser')}updateCounts()}
function money(n){return `₹${Number(n).toLocaleString('en-IN')}`}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function getProduct(id){return state.products.find(p=>p.id===Number(id))||null}
function card(p){const saved=state.wishlist.includes(p.id);return `<article class="product-card" data-id="${p.id}" tabindex="0" aria-label="View ${esc(p.name)}"><div class="product-image" style="--tone:${p.color}"><span class="product-tag">${esc(p.tag)}</span><button class="heart" data-wish="${p.id}" aria-label="${saved?'Remove':'Save'} ${esc(p.name)}">${saved?'♥':'♡'}</button><div class="garment"></div></div><div class="product-info"><h3>${esc(p.name)}</h3><p>${esc(p.category)}${p.oldPrice?' · Sale':''}</p><p class="price">${money(p.price)} ${p.oldPrice?`<del>${money(p.oldPrice)}</del>`:''}</p></div></article>`}
function render(list,el){el.innerHTML=list.map(card).join('');bindCards(el)}
function bindCards(root=document){root.querySelectorAll('.product-card').forEach(c=>{c.onclick=e=>{if(e.target.closest('[data-wish]'))return;openProduct(c.dataset.id)};c.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();openProduct(c.dataset.id)}}});root.querySelectorAll('[data-wish]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleWish(b.dataset.wish)})}
function updateCounts(){$('#wishCount').textContent=state.wishlist.length;$('#cartCount').textContent=state.cart.reduce((a,i)=>a+i.qty,0)}
function filtered(){let list=[...state.products];if(state.filter==='sale')list=list.filter(p=>p.oldPrice);else if(state.filter!=='all')list=list.filter(p=>p.category===state.filter);if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function renderCatalog(){const list=filtered();const names={all:'All pieces',women:"Women's pieces",men:"Men's pieces",accessories:'Accessories',sale:'Sale'};$('#catalogTitle').textContent=names[state.filter];$('#resultCount').textContent=`${list.length} ${list.length===1?'piece':'pieces'}`;render(list,$('#catalogGrid'));$$('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter))}
function toggleWish(id){id=Number(id);state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];persist();render(state.products.filter(p=>p.tag==='NEW'),$('#newGrid'));renderCatalog();if(state.drawer==='wish')openWishlist();if(state.selectedProduct===id)openProduct(id);toast(state.wishlist.includes(id)?'Saved to favourites':'Removed from favourites')}
function addCart(id,size){const p=getProduct(id);if(!p)return;const s=size||p.sizes[0];const item=state.cart.find(x=>x.id===p.id&&x.size===s);item?item.qty++:state.cart.push({id:p.id,size:s,qty:1});persist();toast('Added to bag')}
function changeQty(id,size,delta){const item=state.cart.find(x=>x.id===Number(id)&&x.size===size);if(!item)return;item.qty+=delta;if(item.qty<=0)state.cart=state.cart.filter(x=>!(x.id===Number(id)&&x.size===size));persist();openCart()}
function removeCart(id,size){state.cart=state.cart.filter(x=>!(x.id===Number(id)&&x.size===size));persist();openCart()}
function openProduct(id){const p=getProduct(id);if(!p)return;state.selectedProduct=p.id;state.selectedSize=p.sizes[Math.min(2,p.sizes.length-1)];$('#modalContent').innerHTML=`<div class="modal-inner"><div class="modal-art" style="--tone:${p.color}"><div class="garment"></div></div><div class="modal-copy"><p class="eyebrow">${esc(p.tag)} / ${esc(p.category.toUpperCase())}</p><h2 id="modalTitle">${esc(p.name)}</h2><h3>${money(p.price)} ${p.oldPrice?`<del>${money(p.oldPrice)}</del>`:''}</h3><p>${esc(p.description)}</p><p><b>Details</b><br>Relaxed contemporary fit. Designed as a versatile layer. Illustrative demo imagery.</p><div><b>Size</b><div class="size-row">${p.sizes.map(s=>`<button class="size ${s===state.selectedSize?'selected':''}" data-size="${esc(s)}">${esc(s)}</button>`).join('')}</div></div><button class="btn dark full" id="addProduct">ADD TO BAG</button><button class="btn light full" id="saveProduct">${state.wishlist.includes(p.id)?'SAVED':'SAVE ITEM'}</button></div></div>`;$('#modal').classList.add('open');$('#overlay').classList.add('show');$$('.size').forEach(b=>b.onclick=()=>{$$('.size').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selectedSize=b.dataset.size});$('#addProduct').onclick=()=>{addCart(p.id,state.selectedSize);closeModal();openCart()};$('#saveProduct').onclick=()=>toggleWish(p.id)}
function closeModal(){$('#modal').classList.remove('open');if(!$('#drawer').classList.contains('open'))$('#overlay').classList.remove('show')}
function openDrawer(type){state.drawer=type;$('#drawer').classList.add('open');$('#overlay').classList.add('show');if(type==='bag')openCart();else if(type==='wish')openWishlist();else if(type==='search')openSearch(true);else if(type==='menu')openMenu();else if(type==='account')openAccount()}
function closeDrawer(){state.drawer=null;$('#drawer').classList.remove('open');if(!$('#modal').classList.contains('open'))$('#overlay').classList.remove('show')}
function openCart(){state.drawer='bag';const total=state.cart.reduce((a,i)=>{const p=getProduct(i.id);return a+(p?p.price*i.qty:0)},0);$('#drawerContent').innerHTML=`<p class="eyebrow">YOUR BAG</p><h2 id="drawerTitle">${state.cart.reduce((a,x)=>a+x.qty,0)} items</h2>${state.cart.length?state.cart.map(i=>{const p=getProduct(i.id);return p?`<div class="cart-item"><div class="mini-art" style="--tone:${p.color}"><div class="garment"></div></div><div><b>${esc(p.name)}</b><p>Size ${esc(i.size)}</p><div class="qty"><button data-minus="${p.id}" data-size="${esc(i.size)}">−</button><span>${i.qty}</span><button data-plus="${p.id}" data-size="${esc(i.size)}">+</button></div><p>${money(p.price*i.qty)}</p></div><button class="icon-btn remove" data-remove="${p.id}" data-size="${esc(i.size)}" aria-label="Remove item">×</button></div>`:''}).join(''):`<div class="empty"><p>Your bag is empty.</p><a class="btn dark" href="#new" id="shopEmpty">SHOP NEW</a></div>`}<div class="cart-total"><span>Total</span><span>${money(total)}</span></div>${state.cart.length?'<button class="btn dark full" id="checkout">CHECKOUT</button>':''}`;bindCartControls()}
function bindCartControls(){$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,b.dataset.size,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,b.dataset.size,1));$$('[data-remove]').forEach(b=>b.onclick=()=>removeCart(b.dataset.remove,b.dataset.size));$('#checkout')?.addEventListener('click',openCheckout);$('#shopEmpty')?.addEventListener('click',closeDrawer)}
function openWishlist(){state.drawer='wish';const saved=state.wishlist.map(getProduct).filter(Boolean);$('#drawerContent').innerHTML=`<p class="eyebrow">FAVOURITES</p><h2 id="drawerTitle">${saved.length} saved</h2>${saved.length?saved.map(p=>`<div class="cart-item"><div class="mini-art" style="--tone:${p.color}"><div class="garment"></div></div><div><b>${esc(p.name)}</b><p>${money(p.price)}</p><button class="underline" data-view="${p.id}">View item</button></div><button class="icon-btn remove" data-unwish="${p.id}" aria-label="Remove favourite">×</button></div>`).join(''):'<div class="empty"><p>Save pieces you love and they will appear here.</p><a class="btn dark" href="#new" id="shopFav">SHOP NEW</a></div>'}`;$$('[data-view]').forEach(b=>b.onclick=()=>{closeDrawer();openProduct(b.dataset.view)});$$('[data-unwish]').forEach(b=>b.onclick=()=>toggleWish(b.dataset.unwish));$('#shopFav')?.addEventListener('click',closeDrawer)}
function openSearch(auto=false){state.drawer='search';$('#drawerContent').innerHTML=`<p class="eyebrow">SEARCH</p><h2 id="drawerTitle">Find your next piece</h2><div class="search-box"><input id="searchInput" aria-label="Search products" placeholder="Search products, categories" autocomplete="off"><span>⌕</span></div><div class="result-list" id="results"></div>`;const input=$('#searchInput');input.oninput=()=>renderSearch(input.value);renderSearch('');if(auto)input.focus()}
function renderSearch(q){const query=q.trim().toLowerCase();const list=query?state.products.filter(p=>(`${p.name} ${p.category} ${p.tag}`).toLowerCase().includes(query)):state.products.slice(0,6);$('#results').innerHTML=list.map(p=>`<button data-result="${p.id}">${esc(p.name)}<small> · ${money(p.price)}</small></button>`).join('')||'<p class="muted">No matching pieces.</p>';$$('[data-result]').forEach(b=>b.onclick=()=>{closeDrawer();openProduct(b.dataset.result)})}
function openMenu(){state.drawer='menu';$('#drawerContent').innerHTML=`<p class="eyebrow">MENU</p><h2 id="drawerTitle">Explore VERVE</h2><div class="mobile-links"><a href="#new">New arrivals</a><a href="#catalog" data-category="women">Women</a><a href="#catalog" data-category="men">Men</a><a href="#edit">The Edit</a><a href="#catalog" data-category="accessories">Accessories</a><a href="#catalog" data-category="sale">Sale</a><a href="#services">Stores & services</a></div>`;$$('[data-category]').forEach(a=>a.onclick=()=>{closeDrawer();setFilter(a.dataset.category);setTimeout(()=>$('#catalog').scrollIntoView({behavior:'smooth'}),0)});$$('.mobile-links a:not([data-category])').forEach(a=>a.onclick=closeDrawer)}
function openAccount(){state.drawer='account';$('#drawerContent').innerHTML=`<p class="eyebrow">ACCOUNT</p><h2 id="drawerTitle">Your VERVE</h2><p>Sign in to sync saved items, orders, preferences and recommendations.</p><form id="signInForm"><label for="accountEmail">Email address</label><input id="accountEmail" type="email" required autocomplete="email" placeholder="you@example.com"><button class="btn dark full" type="submit">CONTINUE</button></form><hr><p><b>Guest tools</b></p><p>Order tracking · Saved items · Store finder · Size profile</p>`;$('#signInForm').onsubmit=async e=>{e.preventDefault();await window.VERVE_API.signIn($('#accountEmail').value);toast('Demo sign-in complete');closeDrawer()}}
function openCheckout(){const total=state.cart.reduce((a,i)=>{const p=getProduct(i.id);return a+(p?p.price*i.qty:0)},0);$('#drawerContent').innerHTML=`<p class="eyebrow">CHECKOUT</p><h2 id="drawerTitle">Delivery details</h2><form id="checkoutForm"><label for="checkoutName">Full name</label><input id="checkoutName" required autocomplete="name"><label for="checkoutEmail">Email</label><input id="checkoutEmail" type="email" required autocomplete="email"><label for="checkoutAddress">Address</label><textarea id="checkoutAddress" required rows="3"></textarea><label for="checkoutCity">City</label><input id="checkoutCity" required autocomplete="address-level2"><label for="checkoutPin">PIN code</label><input id="checkoutPin" inputmode="numeric" pattern="[0-9]{6}" required autocomplete="postal-code"><div class="cart-total"><span>Total</span><span>${money(total)}</span></div><button class="btn dark full" type="submit">PLACE DEMO ORDER</button></form>`;$('#checkoutForm').onsubmit=async e=>{e.preventDefault();const result=await window.VERVE_API.createOrder({items:state.cart,total,customer:{name:$('#checkoutName').value,email:$('#checkoutEmail').value,address:$('#checkoutAddress').value,city:$('#checkoutCity').value,pin:$('#checkoutPin').value}});state.cart=[];persist();$('#drawerContent').innerHTML=`<div class="success"><p class="eyebrow">ORDER CONFIRMED</p><h2 id="drawerTitle">Thank you.</h2><p>Your demo order <b>${esc(result.orderId)}</b> has been created locally.</p><button class="btn dark full" id="continueShopping">CONTINUE SHOPPING</button></div>`;$('#continueShopping').onclick=()=>{closeDrawer();location.hash='new'}}}
function setFilter(f){state.filter=f;renderCatalog()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function bindGlobal(){
$('#cartBtn').onclick=()=>{openDrawer('bag');openCart()};$('#wishBtn').onclick=()=>openDrawer('wish');$('#searchBtn').onclick=()=>openDrawer('search');$('#accountBtn').onclick=()=>openDrawer('account');$('#menuBtn').onclick=()=>openDrawer('menu');$('#drawerClose').onclick=closeDrawer;$('#overlay').onclick=()=>{closeDrawer();closeModal()};$('#modalClose').onclick=closeModal;
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();closeModal()}});
$('#closeAnn').onclick=()=>$('#announcement').remove();$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderCatalog()};$$('.filter-btn').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));
$$('[data-category]').forEach(a=>a.onclick=e=>{e.preventDefault();setFilter(a.dataset.category);$('#catalog').scrollIntoView({behavior:'smooth'});if(state.drawer)closeDrawer()});
$('#newsletter').onsubmit=async e=>{e.preventDefault();const email=$('#newsletterEmail').value;await window.VERVE_API.subscribe(email);e.target.reset();toast('Welcome to VERVE Notes')};
window.addEventListener('hashchange',()=>{if(location.hash==='#catalog'&&!state.drawer)$('#catalog').scrollIntoView({behavior:'smooth'})});
}
async function init(){state.products=await window.VERVE_API.getProducts();state.wishlist=state.wishlist.map(Number).filter(id=>getProduct(id));state.cart=state.cart.map(x=>({...x,id:Number(x.id),qty:Number(x.qty)})).filter(x=>getProduct(x.id)&&x.qty>0&&x.size);persist();render(state.products.filter(p=>p.tag==='NEW').slice(0,6),$('#newGrid'));renderCatalog();bindGlobal()}
init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<div class="fatal">Unable to initialize VERVE. Refresh the page.</div>')});
})();
